version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: "postgres:12.8"
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=local_test_db
      - POSTGRES_USER=devtools
      - POSTGRES_PASSWORD=DEVELOPMENT
